### PR TITLE
Add ClojureScript support

### LINKED ISSUE #6: Plans for clojurescript support?
@adambard Have you tried porting Failjure to clojurescript? Failjure uses algo.monads, which just seems to use one function `name-with-attributes`, from clojure.tools.macro. Ie, it doesn't support clojurescript. But [Cats](https://funcool.github.io/cats/latest) does.

Anyways, I thought it would be really nice to reuse tha same Either / Error monadic semantics, on both layers of our application. 

Thoughts?

### PR DESCRIPTION
**Pull request by snorremd**
Fix #6, ClojureScript support.

Adds ClojureScript support via reader conditionals. The HasFailed protocol has
type extensions specific for Clojure and ClojureScript, mainly js/Error and
the `default` type symbol in ClojureScript.

Changed require statements in test namespace to handle import of macros in
ClojureScript mode as ClojureScript does not handle `:refer :all`. Now the
failure.core namespace is aliased under `f` in the test namespace.

Added ClojureScript setup to build.boot file to make running tests in
ClojureScript simple. It also includes ClojureScript and other dependencies
necessary to run a ClojureScript repl.

Signed-off-by: Snorre Magnus Davøen <snorre.davoen@nsd.no>

### CODE REVIEW

**Comment by snorremd** [comment]
I see that the git history marks the test file as deleted rather than moved. This is probably due to how many lines of the files was modified. This could maybe be fixed if I split my pull request into two commits that first move the file and then make the changes. Let me know if you would prefer that approach.

Let me know if you have any other comments on the pull request. I would very much like to use Failjure in my ClojureScript projects.

**Comment by snorremd** [comment]
I discovered that my implementation has a bug for `try*` in ClojureScript. Will have to add some additional tests.

Edit: After reading up about macros and reader conditionals I see that reader conditionals can not be used inside macros. It is therefore necessary to provide a separate `try*` macro for ClojureScript. `try*` is the only platform specific macro I have identified in failjure so far.

The ClojureScript try macro could be called `try-cljs*` or something similar.

**Comment by snorremd** [comment]
I split the changes into two separate commits to clarify the rename of the test file. I also added a test for the `try-cljs*` macro.

**Comment by adambard** [comment]
Absentee maintainer here, I just came across this. It looks great, thanks @snorremd! I should have a chance to test and release it soon.

**Comment by snorremd** [comment]
Sounds great! Thank you for taking the time. I've enjoyed using the Failjure library quite a lot, so porting it to ClojureScript was the least I could do. Let me know if any changes are required.

**Comment by dazld** [comment]
any update on getting this released? I'd like to be able to use failjure in CLJS projects too.

**Comment by adambard** [comment]
@dazld Thanks for the reminder! I've just cleaned up and deployed this PR as version 2.0.0

(Thanks again to @snorremd, and sorry for letting it languish so long)

**Comment by snorremd** [comment]
> @dazld Thanks for the reminder! I've just cleaned up and deployed this PR as version 2.0.0
> 
> (Thanks again to @snorremd, and sorry for letting it languish so long)

No problem at all. Happy to see this getting merged. Implementing `try*` as a try-returning function is a good improvement to make the clj and cljs APIs consistent so thank you for that.

**Pull request merged**
